name: Daily Date Notifier

on:
  workflow_dispatch:

  schedule:
    - cron: "15 9 * * *"

jobs:
  send-email:

    runs-on: ubuntu-latest

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python main.py
